### ISSUE TITLE
Cannot read property 'login' of null

### ISSUE THREAD

**Issue by jrwpatterson** [arup-group/action-notify-unused-branches#3]
Hey,

I'm running this on an older repo with a couple of thousand very old branches I'm getting 

`Cannot read property 'login' of null`

**Comment by romanrzes** [comment]
Hello,

Faced the same issue.

**Comment by peterjgrainger** [comment]
I'll sort this out, sorry :s

**Comment by peterjgrainger** [comment]
@romanrzes @jrwpatterson thanks for spotting this. Can you give v5 a go?
